# Generated by Django 4.2.11 on 2024-03-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
