# Generated by Django 4.2.11 on 2024-03-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_alter_post_edited'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
